version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=analyticsDashb
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass
    ports:
      - "5432:5432"
  web:
    build: .
    ports:
      - "8080:80"
    command: "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:80"
    depends_on:
      - db